preset: symfony

finder:
    path:
        - "src"
        - "tests"

disabled:
    - no_superfluous_phpdoc_tags_symfony
    - phpdoc_annotation_without_dot # This is still buggy: https://github.com/symfony/symfony/pull/19198
    - phpdoc_summary # Currenly some issues 2017-05-13
