language: php

matrix:
    fast_finish: true
    include:
        - php: 7.3
        - php: 7.4
        - php: 8.0

install:
    - composer update --prefer-stable --prefer-dist

script:
    - composer test-ci

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
